# ekart-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekart-app
  namespace: ekart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ekart
  template:
    metadata:
      labels:
        app: ekart
    spec:
      containers:
      - name: ekart
        image: kowsalya13kumar/ekart:latest
        ports:
        - containerPort: 8070

---
apiVersion: v1
kind: Service
metadata:
  name: ekart-service
  namespace: ekart
spec:
  selector:
    app: ekart
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8070
  type: LoadBalancer
